export const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST'
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS'
export const FETCH_PROJECT_REQUEST = 'FETCH_PROJECTS_REQUEST'
export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECTS_SUCCESS'

export const FETCH_ERRORS = 'FETCH_ERRORS'

export const DELETE_PROJECT = 'DLETE_PROJECT'
export const CREATE_PROJECT = 'CREATE_PROJECT'